version: '3'
services:
    mongodb:
        image: mongo:latest
        container_name: 'mongodb'
        environment: 
            - MONGO_INITDB_DATABASE=MindMap
            - MONGO_INITDB_ROOT_USERNAME=MindMap
            - MONGO_INITDB_ROOT_PASSWORD=mindmap
        volumes:
            - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
            - mongodb:/data/db
        ports:
            - '27017-27019:27017-27019'

volumes: 
    mongodb:
